### ISSUE TITLE
运行后首页css格式错误

### ISSUE THREAD

**Issue by jixingxing521** [SzLeaves/mooc_example#1]
运行django项目后，首页的css不正常显示，检查网页，并未报错，也没显示加载错误等。就算我把首页用到的css单独加到index页面内，页面也没有正常显示。

**Comment by SzLeaves** [comment]
应该是静态文件配置问题，尝试修改配置一下 STATICFILES_DIRS

**Comment by SzLeaves** [comment]
> 运行django项目后，首页的css不正常显示，检查网页，并未报错，也没显示加载错误等。就算我把首页用到的css单独加到index页面内，页面也没有正常显示。

应该是静态文件配置问题，尝试修改配置一下 STATICFILES_DIRS

**Comment by SzLeaves** [comment]
我刚刚看了一下，静态文件配置没问题，试试清除浏览器缓存再加载，可以的话放个图看看
